apiVersion: skaffold/v1
kind: Config
metadata:
  name: dev-nestjs-kubernetes
build:
  # local:
  #   push: false
  artifacts:
    - image: docker.io/mstoews/gloss-api-backend
      context: .
      docker:
        dockerfile: dev.Dockerfile
      sync:
        manual:
          - src: 'src/**/*.*'
            dest: .
deploy:
  # kubeContext: docker-desktop
  kubectl:
    flags:
      global: [--namespace=nestjs-kubernetes-namespace]
    manifests:
      - ./kubernetes/03-secrets.yaml
      - ./kubernetes/04-postgres.yaml
      - ./kubernetes/06-minio.yaml
      - ./kubernetes/07-data.yaml
      - ./kubernetes/08-nestjs.yaml
